# Generated by Django 4.0.1 on 2022-01-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
    ]
